plugins {
	id 'com.android.application'
	id 'org.jetbrains.kotlin.android'
	id 'com.google.gms.google-services'
}

android {
	namespace 'com.bandwidth.sample'
	compileSdk 34

	defaultConfig {
//		applicationId "com.bandwidth.sample"
		minSdk 26
		targetSdk 33
		versionCode 1
		versionName "1.0"
		testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
	}

	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
		}
	}
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_11
		targetCompatibility JavaVersion.VERSION_11
	}
	kotlinOptions {
		jvmTarget = '11'
	}
	viewBinding {
		enable = true
	}
}

dependencies {
	implementation fileTree(dir: "libs", include: ["*.aar"])
	implementation project(":webrtc-legacy")
	implementation(libs.bundles.core.bundle)
	implementation 'androidx.appcompat:appcompat:1.6.1'
	implementation 'com.google.android.material:material:1.10.0'
	implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
	implementation 'com.googlecode.libphonenumber:libphonenumber:8.12.36'
    implementation('com.google.firebase:firebase-messaging')
	implementation 'androidx.activity:activity:1.8.0'
	testImplementation(libs.bundles.testing.unit.bundle)

	//implementation 'com.bandwidth:bandwidth-kotlin-webrtc:0.0.2'

	// Add OkHttp3 dependency
	implementation 'com.squareup.okhttp3:okhttp:4.9.1'

	// Add Gson dependency
	implementation 'com.google.code.gson:gson:2.8.8'
	implementation platform('com.google.firebase:firebase-bom:33.2.0')
	implementation("com.google.firebase:firebase-firestore")
}
